### ISSUE TITLE
Remove DApps that allows you to buy digital good

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/dapps-browser#16]
Per App Store Review Team

**Comment by lovincyrus** [comment]
Do you suggest to remove all dapps that allows you to buy digital goods from Trust api (https://trust-api.herokuapp.com/dapps/main) instead ?

**Comment by vikmeup** [comment]
Only for iOS users, I will have special sort for that on the backend, we just need to pass platform ID in the API

**Comment by vikmeup** [comment]
I gonna have a chat with Apple this/next week about details, we might even need to remove marketplaces as well.
