### ISSUE TITLE
Difficult to click on the DApps in the browser / slow

### ISSUE THREAD

**Issue by davecraige** [TrustWallet/dapps-browser#3]
I am having trouble clicking on the DApps inside of the Trust browser.  Is there any way to make the icons and title's clickable?  

Additionally, the load time to get to the next page is very slow.  When you click sometimes it doesn't give you much feedback and load the next page quickly.

**Comment by lovincyrus** [comment]
The icons and titles are clickable as shown here: https://github.com/TrustWallet/dapps-browser/blob/master/src/components/DApps.js#L106

We recently switched from gh-pages to Heroku. I'll look into it! 👌

**Comment by vikmeup** [comment]
Title clickable now, I changed that yesterday. 

We have progress bar on top, we can make it more visible tho

**Comment by davecraige** [comment]
Awesome. Thanks for the updates guys!

**Comment by vikmeup** [comment]
I think this should be fixed now!
