### ISSUE TITLE
Please Update WooshCoin New Contract Logo

### ISSUE THREAD

**Issue by wooshcoin** [TrustWallet/dapps-browser#44]
Please update WooshCoin XWO New Contract Logo
Name: WooshCoin
Symbol: XWO
Decimal: 18
0x5cc00cca0692b9b34af816e5439cdb47d3b63691
our logo link
https://www.wooshcoin.io/logo

And Please Remove our logo from Old Contract
0xb5351d809062cf8e2238bbd2c54af905fb55e42d

**Comment by kolya182** [comment]
For the future request, please make PR in this repo https://github.com/TrustWallet/tokens for now your new logo has been updated https://github.com/TrustWallet/tokens/commit/c240c54f31e49cc05342eb7b20bf4479179d90ab?short_path=e8b8584#diff-e8b8584bcf8c62fb49fa578ae638512e
