### ISSUE TITLE
How to add a dapp to Trust wallet marketplace

### ISSUE THREAD

**Issue by agnelvishal** [TrustWallet/dapps-browser#53]
How to I add a Dapp to Trust wallet marketplace?
I want to list the game http://cryptogame.ml in Trust Wallet

**Comment by kolya182** [comment]
> How to I add a Dapp to Trust wallet marketplace?
> I want to list the game http://cryptogame.ml in Trust Wallet

You can find updated docs here https://github.com/trustwallet/assets#dApp-subbmition-and-listing-requirements
